### ISSUE TITLE
Plugin Error まとめ

### ISSUE THREAD

**Issue by mfmfneko** [mfmfsaba/Issues-Tracker#29]
## MainSystem
- [x] Line.111 `ArrayOutOfBoundsException: "Undefined index: rikiya0403"`
- [x] Line.140 `ArrayOutOfBoundsException: "Undefined index: yumi"`
- [x] Line.493 `Could not pass event 'pocketmine\event\PlayerDeathEvent'`
- [x] Line.493 `UndefinedVariableException: "Undefined variable: level"`
- [x] Line.866 `UndefinedVariableException: "Undefined variable: player"`
- [x] Line.1053 `ArrayOutOfBoundsException: "Undefined index: rikiya0403"`
- [x] Line.1192 `Could not pass event 'pocketmine\event\PlayerJoinEvent'`

**Comment by setsunaMC** [comment]
fix 493 866
